swagger: 2.0
info:
  title: Demo API
  version: 1.0
host: localhost
basePath: /demo/api/v1
produces:
  - application/json
paths:
  /search/{term}:
    get:
      x-dotwebstack-information-product: "http://dotwebstack.org/configuration/SearchData"
      parameters:
        - name: term
          in: path
          description: search term
          required: true
          type: string
          x-dotwebstack-parameter: "http://dotwebstack.org/configuration/TermParameter"
      responses:
        200:
          description: OK
          schema:
            type: array
            required:
              - vocabURI
            items:
              type: object
              properties:
                vocabURI:
                  type: string
                  format: string
                term:
                  type: string
                  format: string
